@startuml
'https://plantuml.com/class-diagram

hide circle

skinparam classAttributeIconSize 0
class InputParser {

    +{static}parseCommand(String userInput) : String
    +{static}parseDetails(String userInput) : String[]
    +{static}parseMealCriteria(String userInput) : MealCategory
}

InputParser ..> MealCategory

enum MealCategory <<enumeration>> {
    GENERAL, BREAKFAST,
    LUNCH, DINNER,
    APPETIZER, DESSERT
}

@enduml